/*
 * 
 */
package uwestore;

import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Patrick Goodson
 */
public class UI extends javax.swing.JFrame
{
    
    /**
     * Creates new form UI
     */
    public UI()
    {
        // Construct controllers
        ItemController.ItemController();
        UserController.UserController();
        
        //Initialise GUI conponents
        initComponents();
        
        // Initialise a table model for the GUI table component.
        DefaultTableModel mTable = (DefaultTableModel) jTableItemsCustomer.getModel();
        mTable.setRowCount(0);

        // Populate table model with items.
        for (Book book : ItemController.getItemList())
        {
            Object[] data = new Object[2];
            data[0] = book.getTitle();
            data[1] = book.getPrice();
            mTable.addRow(data);
        }
        // Managers table should mirror this model
        jTableItemsManager.setModel(mTable);
        
        jComboBoxCustomerSelect.addItem("Select User:");
        for (User user: UserController.getUserList())
        {
            jComboBoxCustomerSelect.addItem(user.getName());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelCustomer = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableItemsCustomer = new javax.swing.JTable();
        jButtonRegister = new javax.swing.JButton();
        jButtonLogin = new javax.swing.JButton();
        jComboBoxCustomerSelect = new javax.swing.JComboBox();
        jLabelSelectName = new javax.swing.JLabel();
        jButtonLogout = new javax.swing.JButton();
        jButtonAddToBasket = new javax.swing.JButton();
        jButtonRemoveFromBasket = new javax.swing.JButton();
        jPanelStoreManager = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableItemsManager = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setMinimumSize(new java.awt.Dimension(100, 100));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(120, 120));

        jPanelCustomer.setMinimumSize(new java.awt.Dimension(100, 100));

        jTableItemsCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String []
            {
                "Name", "Price"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jTableItemsCustomer.setColumnSelectionAllowed(true);
        jTableItemsCustomer.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableItemsCustomer.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableItemsCustomer);
        jTableItemsCustomer.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jButtonRegister.setText("Register with UWE Store");
        jButtonRegister.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonRegisterActionPerformed(evt);
            }
        });

        jButtonLogin.setText("Login");
        jButtonLogin.setEnabled(false);
        jButtonLogin.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonLoginActionPerformed(evt);
            }
        });

        jComboBoxCustomerSelect.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jComboBoxCustomerSelectActionPerformed(evt);
            }
        });

        jLabelSelectName.setText("Select Customer name:");

        jButtonLogout.setText("Logout/Checkout");
        jButtonLogout.setEnabled(false);
        jButtonLogout.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonLogoutActionPerformed(evt);
            }
        });

        jButtonAddToBasket.setText("Add item to basket");
        jButtonAddToBasket.setEnabled(false);
        jButtonAddToBasket.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonAddToBasketActionPerformed(evt);
            }
        });

        jButtonRemoveFromBasket.setText("Remove item from basket");
        jButtonRemoveFromBasket.setEnabled(false);

        javax.swing.GroupLayout jPanelCustomerLayout = new javax.swing.GroupLayout(jPanelCustomer);
        jPanelCustomer.setLayout(jPanelCustomerLayout);
        jPanelCustomerLayout.setHorizontalGroup(
            jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCustomerLayout.createSequentialGroup()
                        .addComponent(jLabelSelectName)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxCustomerSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAddToBasket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonRemoveFromBasket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelCustomerLayout.setVerticalGroup(
            jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRegister)
                    .addComponent(jComboBoxCustomerSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSelectName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCustomerLayout.createSequentialGroup()
                        .addComponent(jButtonAddToBasket)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRemoveFromBasket))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLogin)
                    .addComponent(jButtonLogout))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Customer", jPanelCustomer);

        jTableItemsManager.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String []
            {
                "Name", "Price"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }
        });
        jTableItemsManager.setColumnSelectionAllowed(true);
        jTableItemsManager.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableItemsManager.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTableItemsManager);
        jTableItemsManager.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jButton3.setText("Add item to UWE Store");

        jButton4.setText("Remove Item from UWE Store");

        javax.swing.GroupLayout jPanelStoreManagerLayout = new javax.swing.GroupLayout(jPanelStoreManager);
        jPanelStoreManager.setLayout(jPanelStoreManagerLayout);
        jPanelStoreManagerLayout.setHorizontalGroup(
            jPanelStoreManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelStoreManagerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanelStoreManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelStoreManagerLayout.setVerticalGroup(
            jPanelStoreManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStoreManagerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelStoreManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelStoreManagerLayout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Store Manager", jPanelStoreManager);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 777, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 419, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonRegisterActionPerformed
    {//GEN-HEADEREND:event_jButtonRegisterActionPerformed
        // Add new user.
        
        JTextField memName = new JTextField();
        JTextField memEmail = new JTextField();
        JTextField memAddress = new JTextField();
        

        final JComponent[] inputs = new JComponent[]
        {
            new JLabel("Customer Name:"), memName,
            new JLabel("Customer Email:"), memEmail,
            new JLabel("Customer Address:"), memAddress
        };
        
        int sumbit = JOptionPane.showConfirmDialog(null, inputs, "Enter new customer details",
                JOptionPane.PLAIN_MESSAGE);
        if (sumbit == JOptionPane.OK_OPTION)
        {
            // As only name is required, we discard the email and address data
            UserController.addNewUser(memName.getText());
            // Update combo box
            jComboBoxCustomerSelect.addItem(memName.getText());
            // Confirmation dialogue
            JOptionPane.showMessageDialog(rootPane, "Customer successfully Registered!");
        }
    }//GEN-LAST:event_jButtonRegisterActionPerformed

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonLoginActionPerformed
    {//GEN-HEADEREND:event_jButtonLoginActionPerformed
        // Login curret selected user from the combo box.
        UserController.login((String) jComboBoxCustomerSelect.getSelectedItem());
        // Confirmation dialogue
        JOptionPane.showMessageDialog(rootPane, "Successfully logged in as: " + 
                (String)jComboBoxCustomerSelect.getSelectedItem());
        // Changing state of buttons to control user flow
        jButtonLogin.setEnabled(false);
        jButtonLogout.setEnabled(true);
        jButtonAddToBasket.setEnabled(true);
        jButtonRemoveFromBasket.setEnabled(true);
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jComboBoxCustomerSelectActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jComboBoxCustomerSelectActionPerformed
    {//GEN-HEADEREND:event_jComboBoxCustomerSelectActionPerformed
        // Listen for combo box changing, if it changes to the default state
        // disable the login box
        if (jComboBoxCustomerSelect.getSelectedItem() == "Select User:")
        {
            jButtonLogin.setEnabled(false);
        }
        else
        {
            jButtonLogin.setEnabled(true);
        }
        
    }//GEN-LAST:event_jComboBoxCustomerSelectActionPerformed

    private void jButtonAddToBasketActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonAddToBasketActionPerformed
    {//GEN-HEADEREND:event_jButtonAddToBasketActionPerformed
        // Add to basket selected
        int i = jTableItemsCustomer.getSelectedRow();
        //int j = jTableItemsCustomer.getSelectedColumn();
        // All we need is the 0th column, so we set j to zero
        ItemController.addToBasket((String)jTableItemsCustomer.getValueAt(i, 0));
    }//GEN-LAST:event_jButtonAddToBasketActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonLogoutActionPerformed
    {//GEN-HEADEREND:event_jButtonLogoutActionPerformed
        // Logout/Checkout
        ItemController.checkout();
        jButtonAddToBasket.setEnabled(false);
        jButtonRemoveFromBasket.setEnabled(false);
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonAddToBasket;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JButton jButtonRemoveFromBasket;
    private javax.swing.JComboBox jComboBoxCustomerSelect;
    private javax.swing.JLabel jLabelSelectName;
    private javax.swing.JPanel jPanelCustomer;
    private javax.swing.JPanel jPanelStoreManager;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableItemsCustomer;
    private javax.swing.JTable jTableItemsManager;
    // End of variables declaration//GEN-END:variables
}
